ALTER TABLE "Finding" ADD COLUMN IF NOT EXISTS "dismissed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Finding" ADD COLUMN IF NOT EXISTS "dismissReason" TEXT;
ALTER TABLE "Finding" ADD COLUMN IF NOT EXISTS "dismissedAt" TIMESTAMP(3);
