import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { DownloadFindings } from "@/components/DownloadFindings";
import { PrintButton } from "@/components/PrintButton";
import { ShareLink } from "@/components/ShareLink";
import { StaticScanReport } from "@/components/StaticScanReport";
import { byPriorityThenSeverity } from "@/lib/scan/ordering";

// A clean, static, print-optimized view of a scan report — everything expanded,
// no interactive controls — so the user can print it or Save as PDF to share.

export default async function ScanReportPrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const session = await auth();
  if (!session?.user?.id) redirect("/dashboard");

  const scan = await db.scan.findUnique({
    where: { id },
    include: { findings: true },
  });
  if (!scan || scan.userId !== session.user.id) notFound();
  if (scan.status !== "done") redirect(`/scan/${id}`);

  // Active findings only — dismissed ones aren't part of the shared posture.
  const findings = scan.findings
    .filter((f) => !f.dismissed)
    .sort(byPriorityThenSeverity);

  return (
    <main className="animate-in mx-auto flex w-full max-w-3xl flex-1 flex-col gap-8 px-6 py-10 print:py-4">
      {/* Screen-only toolbar */}
      <div className="flex flex-col gap-4 print:hidden sm:flex-row sm:items-start sm:justify-between">
        <Link
          href={`/scan/${id}`}
          className="text-sm text-muted transition-colors hover:text-foreground"
        >
          ← Back to report
        </Link>
        <div className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-start">
          <ShareLink scanId={id} initialToken={scan.shareToken} />
          <DownloadFindings scanId={id} />
          <PrintButton />
        </div>
      </div>

      <StaticScanReport
        repoFullName={scan.repoFullName}
        score={scan.score}
        scannedAtIso={scan.createdAt.toISOString()}
        findings={findings}
      />

      <footer className="border-t border-line pt-4 text-xs text-muted">
        Generated by Safeship · {scan.repoFullName}
      </footer>
    </main>
  );
}
