import { auth } from "@/auth";
import { db } from "@/lib/db";
import {
  createBranch,
  findOpenPrByHead,
  getDefaultBranch,
  getFileContent,
  GitHubApiError,
  openPullRequest,
  putFile,
} from "@/lib/github/repoFiles";
import { getUserLlmClient } from "@/lib/llm/userClient";
import { LlmRateLimitError } from "@/lib/llm/types";
import { generateFix, isFixablePath, MAX_FIX_FILE_BYTES } from "@/lib/fix/generate";

// "Fix with AI": read the finding's file, ask the LLM for a corrected version,
// then open a pull request with the change on a new branch off the default
// branch. Owner-only, and uses the user's own GitHub token so the commit and PR
// are attributed to them.

export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: "Not signed in" }, { status: 401 });
  }

  const { id } = await params;
  const finding = await db.finding.findUnique({
    where: { id },
    include: { scan: true },
  });
  if (!finding || finding.scan.userId !== session.user.id) {
    return Response.json({ error: "Finding not found" }, { status: 404 });
  }

  if (!finding.filePath) {
    return Response.json(
      { error: "This finding isn't tied to a specific file, so there's nothing to auto-fix." },
      { status: 422 },
    );
  }
  if (!isFixablePath(finding.filePath)) {
    return Response.json(
      {
        error:
          "This is a generated lockfile — update the package and regenerate it instead of editing by hand.",
      },
      { status: 422 },
    );
  }

  const user = await db.user.findUnique({ where: { id: session.user.id } });
  if (!user?.accessToken) {
    return Response.json({ error: "No GitHub token on file — please sign in again." }, { status: 401 });
  }
  const token = user.accessToken;
  const repo = finding.scan.repoFullName;

  const llm = await getUserLlmClient(session.user.id, "fix");
  if (!llm) {
    return Response.json({ error: "The AI isn't configured to generate fixes right now." }, { status: 503 });
  }

  try {
    const file = await getFileContent(repo, finding.filePath, token);
    if (!file) {
      return Response.json(
        { error: "Couldn't read that file from the repo — it may have moved or been deleted." },
        { status: 404 },
      );
    }
    if (file.content.length > MAX_FIX_FILE_BYTES) {
      return Response.json(
        { error: "That file is too large to auto-fix safely. Please fix it manually." },
        { status: 422 },
      );
    }

    const fix = await generateFix(llm, {
      engine: finding.engine,
      ruleId: finding.ruleId,
      severity: finding.severity,
      title: finding.title,
      rawMessage: finding.rawMessage,
      filePath: finding.filePath,
      line: finding.line,
      fileContent: file.content,
    });

    if (!fix.canFix) {
      return Response.json({
        fixed: false,
        note:
          fix.summary ||
          "The AI couldn't produce a safe one-file fix for this. It may need a dependency upgrade or changes across several files.",
      });
    }

    const base = await getDefaultBranch(repo, token);
    const branch = `safeship/fix-${finding.id}`;
    await createBranch(repo, base, branch, token);
    await putFile(
      repo,
      finding.filePath,
      fix.fixedContent,
      `Fix ${finding.ruleId} in ${finding.filePath}`,
      branch,
      file.sha,
      token,
    );

    const title = `Fix: ${finding.title}`.slice(0, 120);
    const body = [
      `Automated fix proposed by **Safeship** for a security finding.`,
      ``,
      `**Finding:** ${finding.title}`,
      `**File:** \`${finding.filePath}\`${finding.line ? ` (around line ${finding.line})` : ""}`,
      `**Engine / rule:** ${finding.engine} · \`${finding.ruleId}\``,
      ``,
      `**What changed:** ${fix.summary || "See the diff."}`,
      ``,
      `> This change was generated by AI. Please review the diff before merging.`,
    ].join("\n");

    let pr;
    try {
      pr = await openPullRequest(repo, branch, base, title, body, token);
    } catch (e) {
      // A PR for this branch likely already exists — return it instead of erroring.
      if (e instanceof GitHubApiError && e.status === 422) {
        const existing = await findOpenPrByHead(repo, branch, token);
        if (existing) {
          return Response.json({
            fixed: true,
            alreadyOpen: true,
            prUrl: existing.htmlUrl,
            prNumber: existing.number,
            summary: fix.summary,
          });
        }
      }
      throw e;
    }

    return Response.json({
      fixed: true,
      prUrl: pr.htmlUrl,
      prNumber: pr.number,
      summary: fix.summary,
    });
  } catch (e) {
    if (e instanceof LlmRateLimitError) {
      return Response.json(
        { error: "The AI is busy right now (rate limit). Give it a moment and try again." },
        { status: 429 },
      );
    }
    if (e instanceof GitHubApiError) {
      const msg =
        e.status === 403
          ? "GitHub refused the change — your access may not allow opening pull requests on this repo."
          : `GitHub error (${e.status}). Please try again.`;
      return Response.json({ error: msg }, { status: 502 });
    }
    console.warn(`[fix ${id}] failed: ${(e as Error).message}`);
    return Response.json({ error: "Couldn't open a fix PR. Please try again." }, { status: 502 });
  }
}
