ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "llmProvider" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "llmBaseUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "llmModel" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "llmApiKeyEnc" TEXT;
